NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.VICTORY_CARD_START_YEAR = 1822
NDefines.NCountry.PS_ATTACK_NATIVES = 0.1
NDefines.NCountry.MONARCH_MIN_SKILL = 1

NDefines.NDiplomacy.DIPLOMAT_SPEED = 100
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5
NDefines.NDiplomacy.EXCOMMUNICATE_ACTION_MONTHS = 6

NDefines.NMilitary.FORT_PER_DEV_RATIO = 100
NDefines.NMilitary.LEADER_GAIN_PERSONALITY_BASE_CHANCE = 100.0

NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_DISABLE_VERSUS_PLAYER_ENEMIES = 1

